# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install OpenSSH
      run: sudo apt install openssh-client -y

    - name: Run SSH script
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p ~/.ssh
          printf "Host *\n\tServerAliveInterval 300\n\tServerAliveCountMax 2" > ~/.ssh/config
          ssh-keyscan -H 142.93.99.41 >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add <(echo "${{ secrets.KEY }}")
          echo "Copying files to server"
          scp -r $GITHUB_WORKSPACE/* root@142.93.99.41:/home/turbohaskell/WebRoot/
